package test;
// Generated 18 avr. 2014 00:52:28 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chercheur generated by hbm2java
 */
@Entity
@Table(name="chercheur"
    ,catalog="pfa1"
)
public class Chercheur  implements java.io.Serializable {


     private Integer idCh;
     private Etablissement etablissementByEtaCodeEtab2;
     private Structurerecherche structurerecherche;
     private Etablissement etablissementByEtaCodeEtab;
     private Chercheur chercheur;
     private User user;
     private Etablissement etablissementByCodeEtab;
     private String nomCh;
     private String prenomCh;
     private Date dateNaisCh;
     private String lieuNaisCh;
     private String sexeCh;
     private String nomJfch;
     private String cinCh;
     private String passCh;
     private String telCh;
     private String emailCh;
     private String gradeCh;
     private String typeCh;
     private String sujetRechCh;
     private Integer avancement;
     private String fonctionCh;
     private Integer annee;
     private String etat;
     private String photo;
     private Set<Inscription> inscriptions = new HashSet<Inscription>(0);
     private Set<Auteur> auteurs = new HashSet<Auteur>(0);
     private Set<Structurerecherche> structurerecherches = new HashSet<Structurerecherche>(0);
     private Set<Chercheur> chercheurs = new HashSet<Chercheur>(0);
     private Set<Obtenir> obtenirs = new HashSet<Obtenir>(0);

    public Chercheur() {
    }

    public Chercheur(Etablissement etablissementByEtaCodeEtab2, Structurerecherche structurerecherche, Etablissement etablissementByEtaCodeEtab, Chercheur chercheur, User user, Etablissement etablissementByCodeEtab, String nomCh, String prenomCh, Date dateNaisCh, String lieuNaisCh, String sexeCh, String nomJfch, String cinCh, String passCh, String telCh, String emailCh, String gradeCh, String typeCh, String sujetRechCh, Integer avancement, String fonctionCh, Integer annee, String etat, String photo, Set<Inscription> inscriptions, Set<Auteur> auteurs, Set<Structurerecherche> structurerecherches, Set<Chercheur> chercheurs, Set<Obtenir> obtenirs) {
       this.etablissementByEtaCodeEtab2 = etablissementByEtaCodeEtab2;
       this.structurerecherche = structurerecherche;
       this.etablissementByEtaCodeEtab = etablissementByEtaCodeEtab;
       this.chercheur = chercheur;
       this.user = user;
       this.etablissementByCodeEtab = etablissementByCodeEtab;
       this.nomCh = nomCh;
       this.prenomCh = prenomCh;
       this.dateNaisCh = dateNaisCh;
       this.lieuNaisCh = lieuNaisCh;
       this.sexeCh = sexeCh;
       this.nomJfch = nomJfch;
       this.cinCh = cinCh;
       this.passCh = passCh;
       this.telCh = telCh;
       this.emailCh = emailCh;
       this.gradeCh = gradeCh;
       this.typeCh = typeCh;
       this.sujetRechCh = sujetRechCh;
       this.avancement = avancement;
       this.fonctionCh = fonctionCh;
       this.annee = annee;
       this.etat = etat;
       this.photo = photo;
       this.inscriptions = inscriptions;
       this.auteurs = auteurs;
       this.structurerecherches = structurerecherches;
       this.chercheurs = chercheurs;
       this.obtenirs = obtenirs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdCh", unique=true, nullable=false)
    public Integer getIdCh() {
        return this.idCh;
    }
    
    public void setIdCh(Integer idCh) {
        this.idCh = idCh;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Eta_CodeEtab2")
    public Etablissement getEtablissementByEtaCodeEtab2() {
        return this.etablissementByEtaCodeEtab2;
    }
    
    public void setEtablissementByEtaCodeEtab2(Etablissement etablissementByEtaCodeEtab2) {
        this.etablissementByEtaCodeEtab2 = etablissementByEtaCodeEtab2;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Code")
    public Structurerecherche getStructurerecherche() {
        return this.structurerecherche;
    }
    
    public void setStructurerecherche(Structurerecherche structurerecherche) {
        this.structurerecherche = structurerecherche;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Eta_CodeEtab")
    public Etablissement getEtablissementByEtaCodeEtab() {
        return this.etablissementByEtaCodeEtab;
    }
    
    public void setEtablissementByEtaCodeEtab(Etablissement etablissementByEtaCodeEtab) {
        this.etablissementByEtaCodeEtab = etablissementByEtaCodeEtab;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Che_IdCh")
    public Chercheur getChercheur() {
        return this.chercheur;
    }
    
    public void setChercheur(Chercheur chercheur) {
        this.chercheur = chercheur;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="passwd", referencedColumnName="Passwd"), 
        @JoinColumn(name="login", referencedColumnName="Login") } )
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CodeEtab")
    public Etablissement getEtablissementByCodeEtab() {
        return this.etablissementByCodeEtab;
    }
    
    public void setEtablissementByCodeEtab(Etablissement etablissementByCodeEtab) {
        this.etablissementByCodeEtab = etablissementByCodeEtab;
    }
    
    @Column(name="NomCh", length=254)
    public String getNomCh() {
        return this.nomCh;
    }
    
    public void setNomCh(String nomCh) {
        this.nomCh = nomCh;
    }
    
    @Column(name="PrenomCh", length=254)
    public String getPrenomCh() {
        return this.prenomCh;
    }
    
    public void setPrenomCh(String prenomCh) {
        this.prenomCh = prenomCh;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateNaisCh", length=19)
    public Date getDateNaisCh() {
        return this.dateNaisCh;
    }
    
    public void setDateNaisCh(Date dateNaisCh) {
        this.dateNaisCh = dateNaisCh;
    }
    
    @Column(name="LieuNaisCh", length=254)
    public String getLieuNaisCh() {
        return this.lieuNaisCh;
    }
    
    public void setLieuNaisCh(String lieuNaisCh) {
        this.lieuNaisCh = lieuNaisCh;
    }
    
    @Column(name="SexeCh", length=254)
    public String getSexeCh() {
        return this.sexeCh;
    }
    
    public void setSexeCh(String sexeCh) {
        this.sexeCh = sexeCh;
    }
    
    @Column(name="NomJFCh", length=254)
    public String getNomJfch() {
        return this.nomJfch;
    }
    
    public void setNomJfch(String nomJfch) {
        this.nomJfch = nomJfch;
    }
    
    @Column(name="CinCh", length=254)
    public String getCinCh() {
        return this.cinCh;
    }
    
    public void setCinCh(String cinCh) {
        this.cinCh = cinCh;
    }
    
    @Column(name="PassCh", length=254)
    public String getPassCh() {
        return this.passCh;
    }
    
    public void setPassCh(String passCh) {
        this.passCh = passCh;
    }
    
    @Column(name="TelCh", length=254)
    public String getTelCh() {
        return this.telCh;
    }
    
    public void setTelCh(String telCh) {
        this.telCh = telCh;
    }
    
    @Column(name="EmailCh", length=254)
    public String getEmailCh() {
        return this.emailCh;
    }
    
    public void setEmailCh(String emailCh) {
        this.emailCh = emailCh;
    }
    
    @Column(name="GradeCh", length=254)
    public String getGradeCh() {
        return this.gradeCh;
    }
    
    public void setGradeCh(String gradeCh) {
        this.gradeCh = gradeCh;
    }
    
    @Column(name="TypeCh", length=254)
    public String getTypeCh() {
        return this.typeCh;
    }
    
    public void setTypeCh(String typeCh) {
        this.typeCh = typeCh;
    }
    
    @Column(name="SujetRechCh", length=254)
    public String getSujetRechCh() {
        return this.sujetRechCh;
    }
    
    public void setSujetRechCh(String sujetRechCh) {
        this.sujetRechCh = sujetRechCh;
    }
    
    @Column(name="Avancement")
    public Integer getAvancement() {
        return this.avancement;
    }
    
    public void setAvancement(Integer avancement) {
        this.avancement = avancement;
    }
    
    @Column(name="FonctionCh", length=254)
    public String getFonctionCh() {
        return this.fonctionCh;
    }
    
    public void setFonctionCh(String fonctionCh) {
        this.fonctionCh = fonctionCh;
    }
    
    @Column(name="Annee")
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }
    
    @Column(name="Etat", length=254)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }
    
    @Column(name="photo", length=254)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="chercheur")
    public Set<Inscription> getInscriptions() {
        return this.inscriptions;
    }
    
    public void setInscriptions(Set<Inscription> inscriptions) {
        this.inscriptions = inscriptions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="chercheur")
    public Set<Auteur> getAuteurs() {
        return this.auteurs;
    }
    
    public void setAuteurs(Set<Auteur> auteurs) {
        this.auteurs = auteurs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="chercheur")
    public Set<Structurerecherche> getStructurerecherches() {
        return this.structurerecherches;
    }
    
    public void setStructurerecherches(Set<Structurerecherche> structurerecherches) {
        this.structurerecherches = structurerecherches;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="chercheur")
    public Set<Chercheur> getChercheurs() {
        return this.chercheurs;
    }
    
    public void setChercheurs(Set<Chercheur> chercheurs) {
        this.chercheurs = chercheurs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="chercheur")
    public Set<Obtenir> getObtenirs() {
        return this.obtenirs;
    }
    
    public void setObtenirs(Set<Obtenir> obtenirs) {
        this.obtenirs = obtenirs;
    }




}


