package test;
// Generated 18 avr. 2014 00:52:28 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Editeur generated by hbm2java
 */
@Entity
@Table(name="editeur"
    ,catalog="pfa1"
)
public class Editeur  implements java.io.Serializable {


     private Integer idEd;
     private String nomEd;
     private String prenomEd;

    public Editeur() {
    }

    public Editeur(String nomEd, String prenomEd) {
       this.nomEd = nomEd;
       this.prenomEd = prenomEd;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdEd", unique=true, nullable=false)
    public Integer getIdEd() {
        return this.idEd;
    }
    
    public void setIdEd(Integer idEd) {
        this.idEd = idEd;
    }
    
    @Column(name="NomEd", length=254)
    public String getNomEd() {
        return this.nomEd;
    }
    
    public void setNomEd(String nomEd) {
        this.nomEd = nomEd;
    }
    
    @Column(name="PrenomEd", length=254)
    public String getPrenomEd() {
        return this.prenomEd;
    }
    
    public void setPrenomEd(String prenomEd) {
        this.prenomEd = prenomEd;
    }




}


