package test;
// Generated 18 avr. 2014 00:52:28 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InscriptionId generated by hbm2java
 */
@Embeddable
public class InscriptionId  implements java.io.Serializable {


     private int idCh;
     private String code;

    public InscriptionId() {
    }

    public InscriptionId(int idCh, String code) {
       this.idCh = idCh;
       this.code = code;
    }
   

    @Column(name="IdCh", nullable=false)
    public int getIdCh() {
        return this.idCh;
    }
    
    public void setIdCh(int idCh) {
        this.idCh = idCh;
    }

    @Column(name="Code", nullable=false, length=254)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InscriptionId) ) return false;
		 InscriptionId castOther = ( InscriptionId ) other; 
         
		 return (this.getIdCh()==castOther.getIdCh())
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCh();
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         return result;
   }   


}


