package test;
// Generated 18 avr. 2014 00:52:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Universite generated by hbm2java
 */
@Entity
@Table(name="universite"
    ,catalog="pfa1"
)
public class Universite  implements java.io.Serializable {


     private int codeUniv;
     private String libUniv;
     private Set<Etablissement> etablissements = new HashSet<Etablissement>(0);

    public Universite() {
    }

	
    public Universite(int codeUniv) {
        this.codeUniv = codeUniv;
    }
    public Universite(int codeUniv, String libUniv, Set<Etablissement> etablissements) {
       this.codeUniv = codeUniv;
       this.libUniv = libUniv;
       this.etablissements = etablissements;
    }
   
     @Id 
    
    @Column(name="CodeUniv", unique=true, nullable=false)
    public int getCodeUniv() {
        return this.codeUniv;
    }
    
    public void setCodeUniv(int codeUniv) {
        this.codeUniv = codeUniv;
    }
    
    @Column(name="LibUniv", length=254)
    public String getLibUniv() {
        return this.libUniv;
    }
    
    public void setLibUniv(String libUniv) {
        this.libUniv = libUniv;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="universite")
    public Set<Etablissement> getEtablissements() {
        return this.etablissements;
    }
    
    public void setEtablissements(Set<Etablissement> etablissements) {
        this.etablissements = etablissements;
    }




}


