package modele;
// Generated 1 juin 2014 14:56:19 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name="diplome"
    ,catalog="pfa1"
)
public class Diplome  implements java.io.Serializable {


     private int idD;
     private Integer intituleD;
     private Set<Obtenir> obtenirs = new HashSet<Obtenir>(0);

    public Diplome() {
    }

	
    public Diplome(int idD) {
        this.idD = idD;
    }
    public Diplome(int idD, Integer intituleD, Set<Obtenir> obtenirs) {
       this.idD = idD;
       this.intituleD = intituleD;
       this.obtenirs = obtenirs;
    }
   
     @Id 
    
    @Column(name="Id_D", unique=true, nullable=false)
    public int getIdD() {
        return this.idD;
    }
    
    public void setIdD(int idD) {
        this.idD = idD;
    }
    
    @Column(name="Intitule_D")
    public Integer getIntituleD() {
        return this.intituleD;
    }
    
    public void setIntituleD(Integer intituleD) {
        this.intituleD = intituleD;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="diplome")
    public Set<Obtenir> getObtenirs() {
        return this.obtenirs;
    }
    
    public void setObtenirs(Set<Obtenir> obtenirs) {
        this.obtenirs = obtenirs;
    }




}


