package modele;
// Generated 1 juin 2014 14:56:19 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ecrire generated by hbm2java
 */
@Entity
@Table(name="ecrire"
    ,catalog="pfa1"
)
public class Ecrire  implements java.io.Serializable {


     private EcrireId id;
     private Publication publication;
     private Auteur auteur;
     private Integer rang;

    public Ecrire() {
    }

	
    public Ecrire(EcrireId id, Publication publication, Auteur auteur) {
        this.id = id;
        this.publication = publication;
        this.auteur = auteur;
    }
    public Ecrire(EcrireId id, Publication publication, Auteur auteur, Integer rang) {
       this.id = id;
       this.publication = publication;
       this.auteur = auteur;
       this.rang = rang;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idPub", column=@Column(name="IdPub", nullable=false) ), 
        @AttributeOverride(name="idAut", column=@Column(name="IdAut", nullable=false) ) } )
    public EcrireId getId() {
        return this.id;
    }
    
    public void setId(EcrireId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdPub", nullable=false, insertable=false, updatable=false)
    public Publication getPublication() {
        return this.publication;
    }
    
    public void setPublication(Publication publication) {
        this.publication = publication;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdAut", nullable=false, insertable=false, updatable=false)
    public Auteur getAuteur() {
        return this.auteur;
    }
    
    public void setAuteur(Auteur auteur) {
        this.auteur = auteur;
    }
    
    @Column(name="rang")
    public Integer getRang() {
        return this.rang;
    }
    
    public void setRang(Integer rang) {
        this.rang = rang;
    }

    @Override
    public String toString() {
        return  auteur +"";
    }




}


